[package]
name = "jintemplify"
version = "0.1.3"
edition = "2021"
description = "A tool to compose files using Jinja2 templates and YAML variables."
license = "MIT"
repository = "https://github.com/fantajeon/jintemplify"
homepage = "https://github.com/fantajeon/jintemplify"
documentation = "https://github.com/fantajeon/jintemplify"
authors = ["Hyeokjune Jeon <fantajeon@gmail.com>"]
exclude = ["tests/**", "examples/**"]

[dependencies]
tera = "1"
clap = "2"
serde_yaml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
anyhow = "1.0"
log = "0.4"
env_logger = "0.9"


[profile.release]
opt-level = "z" # 최대 크기 최적화
lto = true      # 링크 시간 최적화
