name: Build and Deploy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build APK package inside Alpine container
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace alpine:latest /bin/ash -c "\
            apk add alpine-sdk cargo && \
            adduser -D builder && \
            abuild-keygen -a -n && \
            chown -R builder /workspace && \
            su builder -c 'abuild -r'
          "

      - name: Deploy to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jintemplify-*.apk
          asset_name: jintemplify.apk
          asset_content_type: application/vnd.alpine.package-archive
