name: Build and Deploy APK

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Alpine environment
        uses: docker://alpine:latest
        with:
          entrypoint: /bin/ash

      - name: Install dependencies
        run: |
          apk add alpine-sdk cargo

      - name: Build APK package
        run: |
          abuild-keygen -a -i
          abuild -r

      - name: Deploy to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./jintemplify-*.apk
          asset_name: jintemplify.apk
          asset_content_type: application/vnd.alpine.package-archive
