name: Build and Deploy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build APK package inside Alpine container
        run: |
          docker run --rm -v $(pwd):/workspace -v $(pwd)/output:/home/builder/packages -w /workspace alpine:latest /bin/ash -c "\
            apk add alpine-sdk cargo && \
            adduser -D -G abuild builder && \
            chown -R builder /workspace && \
            chown -R builder /var/cache/distfiles/ && \
            su builder -c 'abuild-keygen -a -n' && \
            cp /home/builder/.abuild/*.rsa.pub /etc/apk/keys/ && \
            su builder -c 'abuild checksum' && \
            su builder -c 'abuild -r'
          "
          tree $(pwd)/output/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./output/x86_64/jintemplify-*.apk
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
